runtime: nodejs18
env_variables:
  TELEGRAM_BOT_TOKEN: "YOUR_TELEGRAM_BOT_TOKEN"
  DATABASE_URL: "YOUR_DATABASE_URL"
  PASSWORD: "YOUR_PASSWORD"
  APP_URL: "YOUR_APP_URL"
  WEBHOOK_SECRET: "YOUR_WEBHOOK_SECRET"
